const components = [
  "",
  "Rating",
  "Layout",
  "Transition",
  "Navbar",
  "Modal",
  "Text",
  "Drag",
  "Drag and Drop",
  "Input",
  "Dropdown",
  "Select",
  "Card",
  "Cursor",
  "List",
  "Button",
  "Scroll",
  "NotAssigned",
  "Progress",
  "Loader",
  "Tabs",
  "Data",
  "Calendar",
  "Image",
  "Picker",
  "Table",
  "Stepper",
  "All",
  "DoneItem",
  "Page",
  "Widget",
];

const codepens = [
  {
    title: "Card for Tasks",
    link: "https://codepen.io/lezzles11/pen/NWvEaYy",
    importance: "high",
    sparkJoy: true,
    where: "Dashboard",
    component: "Card",
    reference: false,
  },
  {
    title: "Table Design",
    link: "https://codepen.io/lezzles11/pen/Jjyerpj",
    importance: "high",
    sparkJoy: true,
    where: "Tasks",
    component: "Table",
    reference: false,
  },
  {
    title: "Footer",
    link: "https://codepen.io/lezzles11/pen/GRvwmYE",
    importance: "high",
    sparkJoy: true,
    where: "All",
    component: "Footer",
    reference: false,
  },
  {
    title: "Layout with Sidenav",
    link: "https://codepen.io/lezzles11/pen/qBXQXKQ",
    importance: "high",
    sparkJoy: true,
    where: "All",
    component: "Layout",
    reference: false,
  },
  {
    title: "Layout Dashboard",
    link: "https://codepen.io/lezzles11/pen/PoKxJGW",
    importance: "high",
    sparkJoy: true,
    where: "Dashboard",
    component: "Layout",
    reference: true,
  },
  {
    title: "Layout Signup / Set / Onboarding",
    link: "https://codepen.io/lezzles11/pen/GRvwMjj",
    importance: "high",
    sparkJoy: true,
    where: "Signup",
    component: "Layout",
    reference: true,
  },
  {
    title: "Layout Projects",
    link: "https://codepen.io/lezzles11/live/QWMJqpQ",
    importance: "high",
    sparkJoy: true,
    where: "Projects",
    component: "Layout",
    reference: true,
  },
  {
    title: "Layout Search",
    link: "https://codepen.io/havardob/pen/jOwJWOG",
    importance: "high",
    sparkJoy: true,
    where: "Tasks",
    component: "",
    reference: true,
  },

  {
    title: "Layout Dashboard",
    link: "https://codepen.io/lezzles11/pen/NWvEved",
    importance: "high",
    sparkJoy: true,
    where: "Dashboard",
    component: "Layout",
    reference: false,
  },
  {
    title: "Layout Dashboard",
    link: "https://codepen.io/lezzles11/pen/qBXQPVB",
    importance: "high",
    sparkJoy: true,
    where: "Dashboard",
    component: "Layout",
    reference: false,
  },
  {
    title: "Layout Flex Reference",
    link: "https://codepen.io/lezzles11/pen/vYJQeJK",
    importance: "high",
    sparkJoy: true,
    where: "All",
    component: "Layout",
    reference: true,
  },
  {
    title: "Layout Tasks",
    link: "https://codepen.io/lezzles11/pen/bGrQrPg",
    importance: "high",
    sparkJoy: true,
    where: "Tasks",
    component: "",
    reference: true,
  },
  {
    title: "Layout Bugs",
    link: "https://codepen.io/lezzles11/live/KKvrXWR",
    importance: "high",
    sparkJoy: true,
    where: "Bugs",
    component: "",
    reference: true,
  },
  {
    title: "Layout Features",
    link: "https://codepen.io/matt-harris/full/dyPjapE",
    importance: "high",
    sparkJoy: true,
    where: "Features",
    component: "",
    reference: true,
  },
  {
    title: "Layout Calendar",
    link: "https://codepen.io/lezzles11/pen/wvqQrqr",
    importance: "high",
    sparkJoy: true,
    where: "Calendar",
    component: "Layout",
    reference: true,
  },

  {
    title: "Layout Projects",
    link: "https://codepen.io/aybukeceylan/pen/OJRNbZp",
    importance: "high",
    sparkJoy: true,
    where: "Projects",
    component: "Layout",
    reference: true,
  },
  {
    title: "Layout for all headers",
    link: "https://codepen.io/lezzles11/pen/vYJQeXL",
    importance: "high",
    sparkJoy: true,
    where: "All",
    component: "Layout",
    reference: true,
  },
  {
    title: "Form initial values",
    link: "https://codesandbox.io/s/react-final-form-initial-values-grrr7",
    importance: "high",
    sparkJoy: false,
    where: "Features",
    component: "",
    reference: false,
  },
  {
    title: "Drag and Drop with Form",
    link: "https://codesandbox.io/s/react-final-form-field-arrays-react-beatiful-dnd-as-drag-drop-forked-jdjwj",
    importance: "high",
    sparkJoy: false,
    where: "Features",
    component: "Drag and Drop",
    reference: false,
  },
  {
    title: "Accordian",
    link: "https://codesandbox.io/embed/framer-motion-accordion-qx958?codemirror=1",
    importance: "",
    sparkJoy: true,
    where: "All",
    component: "Accordian",
    reference: false,
  },
  {
    title: "Framer Toggle To Emphasize",
    link: "https://codesandbox.io/embed/framer-motion-magic-expand-hwugd",
    importance: "low",
    sparkJoy: false,
    where: "Modal",
    component: "Modal",
    reference: false,
  },
  {
    title: "feedback",
    link: "https://codepen.io/aaroniker/pen/mdyYBPP",
    importance: "med",
    sparkJoy: true,
    where: "Dashboard",
    component: "Rating",
    reference: true,
  },
  {
    title: "layout",
    link: "https://codesandbox.io/embed/material-ui-layout-7mn9xq3nnj?file:/src/index.js",
    importance: "high",
    sparkJoy: false,
    where: "",
    component: "Layout",
    reference: false,
  },
  {
    title: "layout",
    link: "https://react.semantic-ui.com/layouts/",
    importance: "high",
    sparkJoy: false,
    where: "",
    component: "Layout",
    reference: false,
  },
  {
    title: "layout",
    link: "https://codepen.io/simeydotme/pen/rNVaOap",
    importance: "high",
    sparkJoy: false,
    where: "",
    component: "Layout",
    reference: false,
  },
  {
    title: "transitionsAndModals",
    link: "https://codesandbox.io/embed/zsk52",
    importance: "medium",
    sparkJoy: false,
    where: "",
    component: "Transition",
    reference: false,
  },
  {
    title: "Favicon",
    link: "https://gauger.io/fonticon/",
    importance: "high",
    sparkJoy: true,
    where: "All",
    component: "Navbar",
    reference: true,
  },
  {
    title: "Favicon",
    link: "https://codesandbox.io/embed/react-page-transitions-1jgim?from-embed",
    importance: "medium",
    sparkJoy: false,
    where: "",
    component: "Modal",
    reference: false,
  },
  {
    title: "texttransitions",
    link: "https://codesandbox.io/embed/react-router-gsap-page-transitions-3ev3k",
    importance: "high",
    sparkJoy: true,
    where: "",
    component: "Text",
    reference: false,
  },
  {
    title: "texttransitions",
    link: "https://codesandbox.io/embed/github/darbley/react-page-slide-transitions/tree/master/?from-embed",
    importance: "high",
    sparkJoy: false,
    where: "Tasks",
    component: "Transition",
    reference: false,
  },
  {
    title: "font",
    link: "https://codepen.io/jpamental/pen/VEYzxO",
    importance: "medium",
    sparkJoy: false,
    where: "",
    component: "Text",
    reference: false,
  },
  {
    title: "font",
    link: "https://codepen.io/MadeByMike/pen/GmBLKo",
    importance: "medium",
    sparkJoy: false,
    where: "",
    component: "Text",
    reference: false,
  },
  {
    title: "font",
    link: "https://codepen.io/lisilinhart/pen/MoLxxp",
    importance: "med",
    sparkJoy: true,
    where: "Home",
    component: "Text",
    reference: true,
  },
  {
    title: "draganddrop",
    link: "https://codesandbox.io/embed/github/guandjoy/rudl-demo/tree/master/",
    importance: "medium",
    sparkJoy: true,
    where: "All",
    component: "Layout",
    reference: false,
  },
  {
    title: "draganddrop",
    link: "https://codesandbox.io/embed/framer-motion-dnd-y2wxq",
    importance: "medium",
    sparkJoy: true,
    where: "",
    component: "Drag",
    reference: false,
  },
  {
    title: "draganddrop",
    link: "https://codesandbox.io/embed/framer-motion-5-drag-to-reorder-lists-uonye",
    importance: "medium",
    sparkJoy: true,
    where: "Features",
    component: "Drag and Drop",
    reference: false,
  },
  {
    title: "clickonprojects",
    link: "https://codesandbox.io/embed/scroll-animation-with-react-spring-forked-ekxlf",
    importance: "low",
    sparkJoy: false,
    where: "",
    component: "Text",
    reference: false,
  },
  {
    title: "Focus On Features Circle ",
    link: "https://codesandbox.io/embed/framer-motion-2-animatesharedlayout-animate-between-different-components-dy0bv?file:/src/App.js",
    importance: "low",
    sparkJoy: true,
    where: "",
    component: "Transition",
    reference: false,
  },
  {
    title: "nav",
    link: "https://codesandbox.io/embed/framer-motion-page-transition-jb7d0",
    importance: "high",
    sparkJoy: true,
    where: "",
    component: "Navbar",
    reference: false,
  },
  {
    title: "purecssform",
    link: "https://codepen.io/team/css-tricks/pen/XBmazq",
    importance: "high",
    sparkJoy: true,
    where: "Features",
    component: "Input",
    reference: false,
  },
  {
    title: "Navbar Dropdpown",
    link: "https://codesandbox.io/embed/framer-motion-radix-menu-forked-02z77",
    importance: "low",
    sparkJoy: true,
    where: "",
    component: "Dropdown",
    reference: false,
  },
  {
    title: "dropdowns",
    link: "https://react.semantic-ui.com/modules/dropdown/",
    importance: "low",
    sparkJoy: true,
    where: "",
    component: "Select",
    reference: true,
  },
  {
    title: "tasksemphasis",
    link: "https://codepen.io/hexagoncircle/pen/jgGxKR",
    importance: "high",
    sparkJoy: false,
    where: "Modal",
    component: "Card",
    reference: false,
  },
  {
    title: "tasksemphasis",
    link: "https://codepen.io/eglenfield/pen/jObJjYR",
    importance: "high",
    sparkJoy: true,
    where: "",
    component: "Cursor",
    reference: false,
  },
  {
    title: "dragtoview",
    link: "https://codesandbox.io/embed/framer-motion-apple-watch-app-menu-mq8s8",
    importance: "low",
    sparkJoy: false,
    where: "",
    component: "Drag",
    reference: false,
  },
  {
    title: "Accordian",
    link: "https://codesandbox.io/embed/framer-motion-list-transitions-forked-nqd2r",
    importance: "low",
    sparkJoy: false,
    where: "",
    component: "List",
    reference: false,
  },
  {
    title: "Framer Navbar",
    link: "https://codesandbox.io/s/framer-motion-side-menu-forked-ueki9",
    importance: "high",
    sparkJoy: true,
    where: "All",
    component: "Navbar",
    reference: false,
  },
  {
    title: "swipetodelete",
    link: "https://codesandbox.io/embed/the-framer-book-example-animations-35-swipe-to-delete-z9hqi?file:/src/index.js",
    importance: "low",
    sparkJoy: false,
    where: "",
    component: "Drag",
    reference: false,
  },
  {
    title: "cards",
    link: "https://codesandbox.io/embed/react-spring-list-tzeze",
    importance: "high",
    sparkJoy: false,
    where: "",
    component: "List",
    reference: false,
  },
  {
    title: "Google Layout",
    link: "https://codesandbox.io/embed/mmut9",
    importance: "high",
    sparkJoy: false,
    where: "",
    component: "Layout",
    reference: false,
  },
  {
    title: "cards",
    link: "https://codesandbox.io/embed/6jlvz1j5q3",
    importance: "high",
    sparkJoy: true,
    where: "Bugs",
    component: "Card",
    reference: false,
  },
  {
    title: "buttons",
    link: "https://codesandbox.io/embed/hamburger-menu-with-framer-motion-iwxtp",
    importance: "high",
    sparkJoy: true,
    where: "Modal",
    component: "Button",
    reference: false,
  },
  {
    title: "Click to Scroll, Cool Hover",
    link: "https://codepen.io/giannotr/pen/GPgKpK",
    importance: "high",
    sparkJoy: false,
    where: "",
    component: "Scroll",
    reference: false,
  },
  {
    title: "Nav Buttons Hover",
    link: "https://codepen.io/oliviale/pen/gKParr",
    importance: "high",
    sparkJoy: true,
    where: "",
    component: "Button",
    reference: false,
  },
  {
    title: "buttons",
    link: "socialmedia",
    importance: "high",
    sparkJoy: false,
    where: "",
    component: "NotAssigned",
    reference: false,
  },
  {
    title: "playbutton",
    link: "https://codesandbox.io/embed/llvqmkxnkz",
    importance: "",
    sparkJoy: false,
    where: "",
    component: "Button",
    reference: false,
  },
  {
    title: "Play SVG Button",
    link: "https://codepen.io/Zaku/pen/YjRqzB",
    importance: "",
    sparkJoy: false,
    where: "",
    component: "Button",
    reference: false,
  },
  {
    title: "playbutton",
    link: "https://codepen.io/pirrera/pen/bqVeGx",
    importance: "high",
    sparkJoy: true,
    where: "All",
    component: "Button",
    reference: false,
  },
  {
    title: "loadingcards",
    link: "https://codepen.io/juliepark/pen/vjMOKQ",
    importance: "medium",
    sparkJoy: true,
    where: "",
    component: "Card",
    reference: false,
  },
  {
    title: "loadingcards",
    link: "https://codepen.io/lewisvrobinson/pen/WJpzMZ",
    importance: "medium",
    sparkJoy: true,
    where: "",
    component: "Progress",
    reference: false,
  },
  {
    title: "reactsuspense",
    link: "https://codesandbox.io/embed/4wnpo9oy4",
    importance: "high",
    sparkJoy: true,
    where: "",
    component: "Loader",
    reference: true,
  },
  {
    title: "reactsuspense",
    link: "https://codesandbox.io/embed/j4wrxnm14v",
    importance: "high",
    sparkJoy: true,
    where: "",
    component: "Loader",
    reference: true,
  },
  {
    title: "reactsuspense",
    link: "https://codesandbox.io/s/react-suspense-esc8w",
    importance: "high",
    sparkJoy: true,
    where: "",
    component: "Loader",
    reference: true,
  },
  {
    title: "Loading",
    link: "https://codesandbox.io/embed/8nq4w3jj39",
    importance: "high",
    sparkJoy: false,
    where: "",
    component: "Loader",
    reference: true,
  },
  {
    title: "Input Label",
    link: "https://codesandbox.io/embed/r0kzgevzk",
    importance: "",
    sparkJoy: false,
    where: "",
    component: "Input",
    reference: false,
  },
  {
    title: "Editable Text",
    link: "https://codepen.io/mjunaidi/pen/KXKNmv",
    importance: "",
    sparkJoy: true,
    where: "",
    component: "Input",
    reference: false,
  },
  {
    title: "Line Slides on Input",
    link: "https://codepen.io/ainalem/pen/EQXjOR",
    importance: "",
    sparkJoy: true,
    where: "",
    component: "Input",
    reference: false,
  },
  {
    title: "toggles",
    link: "https://codesandbox.io/embed/y0x4k4qjwz",
    importance: "low",
    sparkJoy: false,
    where: "",
    component: "Input",
    reference: false,
  },
  {
    title: "Toggle Card, Cool How it pops up",
    link: "https://codepen.io/janeRivas/pen/pZjxoa",
    importance: "low",
    sparkJoy: true,
    where: "EachBug",
    component: "Card",
    reference: false,
  },
  {
    title: "toggles",
    link: "https://codepen.io/borntofrappe/pen/aboPapm",
    importance: "low",
    sparkJoy: true,
    where: "",
    component: "Input",
    reference: false,
  },
  {
    title: "template",
    link: "https://codesandbox.io/embed/hack4impact-website-0kn5m",
    importance: "high",
    sparkJoy: false,
    where: "",
    component: "Layout",
    reference: true,
  },
  {
    title: "template",
    link: "https://mui.com/getting-started/templates/",
    importance: "high",
    sparkJoy: true,
    where: "All",
    component: "Layout",
    reference: false,
  },
  {
    title: "template",
    link: "https://codepen.io/kathykato/pen/KRQOKY",
    importance: "high",
    sparkJoy: true,
    where: "Features",
    component: "Layout",
    reference: false,
  },
  {
    title: "template",
    link: "https://codepen.io/mxbck/pen/ERNwBy",
    importance: "high",
    sparkJoy: true,
    where: "Bugs",
    component: "Layout",
    reference: false,
  },
  {
    title: "tabs",
    link: "https://codesandbox.io/embed/festive-ramanujan-byw7s",
    importance: "hig",
    sparkJoy: true,
    where: "",
    component: "Tabs",
    reference: false,
  },
  {
    title: "tabs",
    link: "https://codesandbox.io/embed/framer-motion-animated-tabs-jkckb",
    importance: "high",
    sparkJoy: false,
    where: "",
    component: "Tabs",
    reference: false,
  },
  {
    title: "tabs",
    link: "https://codepen.io/ettrics/pen/WRbGRN",
    importance: "hig",
    sparkJoy: true,
    where: "Projects",
    component: "Navbar",
    reference: false,
  },
  {
    title: "Template Of Cards",
    link: "https://codesandbox.io/embed/631sl",
    importance: "high",
    sparkJoy: true,
    where: "",
    component: "Layout",
    reference: false,
  },
  {
    title: "scrolltoreveal",
    link: "https://codesandbox.io/embed/flexboxyoga-in-webgl-7psew",
    importance: "high",
    sparkJoy: true,
    where: "",
    component: "Layout",
    reference: false,
  },
  {
    title: "hover",
    link: "https://codepen.io/avstorm/pen/oqKbLq",
    importance: "medium",
    sparkJoy: true,
    where: "Login",
    component: "Button",
    reference: false,
  },
  {
    title: "Hello Button",
    link: "https://codepen.io/short/pen/VyNqPa",
    importance: "medium",
    sparkJoy: false,
    where: "",
    component: "Button",
    reference: false,
  },
  {
    title: "Download Button",
    link: "https://codepen.io/cobra_winfrey/pen/opZgWL",
    importance: "medium",
    sparkJoy: true,
    where: "Tasks",
    component: "Button",
    reference: false,
  },
  {
    title: "graphs",
    link: "https://codesandbox.io/embed/z6r7qj8wm",
    importance: "med",
    sparkJoy: false,
    where: "",
    component: "Data",
    reference: false,
  },
  {
    title: "graphs",
    link: "https://codepen.io/hougasian/pen/vewKaX",
    importance: "hig",
    sparkJoy: false,
    where: "",
    component: "Data",
    reference: false,
  },
  {
    title: "MUI Calendar",
    link: "https://codesandbox.io/embed/0y4zvoxl8v",
    importance: "",
    sparkJoy: true,
    where: "Calendar",
    component: "Calendar",
    reference: false,
  },
  {
    title: "calendar",
    link: "https://codepen.io/team/amcharts/pen/ExjbjbJ",
    importance: "",
    sparkJoy: true,
    where: "",
    component: "Calendar",
    reference: false,
  },
  {
    title: "codeeditor",
    link: "https://codesandbox.io/embed/r1y0z1mx4",
    importance: "",
    sparkJoy: false,
    where: "",
    component: "Text",
    reference: false,
  },
  {
    title: "purecssstory",
    link: "https://codepen.io/jcoulterdesign/pen/oRRRPY",
    importance: "",
    sparkJoy: false,
    where: "",
    component: "Card",
    reference: false,
  },
  {
    title: "images",
    link: "https://codesandbox.io/embed/framer-motion-lazy-load-images-bx1je?file:/src/App.js",
    importance: "high",
    sparkJoy: true,
    where: "Projects",
    component: "Image",
    reference: false,
  },
  {
    title: "Clock with progress rings",
    link: "https://codesandbox.io/embed/react-progress-rings-clock-69z4j",
    importance: "high",
    sparkJoy: false,
    where: "",
    component: "Progress",
    reference: false,
  },
  {
    title: "progress",
    link: "https://codepen.io/hakimel/pen/BpKNPg",
    importance: "high",
    sparkJoy: true,
    where: "Features",
    component: "Navbar",
    reference: false,
  },
  {
    title: "progress",
    link: "https://codepen.io/lmgonzalves/pen/NyzKdr",
    importance: "high",
    sparkJoy: false,
    where: "",
    component: "Progress",
    reference: false,
  },
  {
    title: "colors",
    link: "https://casesandberg.github.io/react-color/",
    importance: "high",
    sparkJoy: true,
    where: "All",
    component: "Picker",
    reference: false,
  },
  {
    title: "tables",
    link: "https://codesandbox.io/embed/429yzl5pj7?file:/src/index.js",
    importance: "high",
    sparkJoy: true,
    where: "All",
    component: "Table",
    reference: false,
  },
  {
    title: "tables",
    link: "https://codesandbox.io/embed/material-ui-editable-tables-wsp0c",
    importance: "high",
    sparkJoy: false,
    where: "",
    component: "Table",
    reference: false,
  },
  {
    title: "Framer Animation Reference",
    link: "https://codesandbox.io/embed/framer-motion-basic-usage-90q89",
    importance: "high",
    sparkJoy: false,
    where: "",
    component: "Card",
    reference: true,
  },
  {
    title: "dashboard",
    link: "http://dashboards.webkom.co/react/airframe/dashboards/projects",
    importance: "high",
    sparkJoy: false,
    where: "Dashboard",
    component: "Data",
    reference: false,
  },
  {
    title: "diagrams",
    link: "https://antonioru.github.io/beautiful-react-diagrams/#/Schema",
    importance: "high",
    sparkJoy: false,
    where: "",
    component: "Data",
    reference: false,
  },
  {
    title: "checkbox",
    link: "https://codepen.io/finnhvman/pen/zpygBB",
    importance: "high",
    sparkJoy: true,
    where: "Settings",
    component: "Input",
    reference: false,
  },
  {
    title: "uploadfile",
    link: "https://codepen.io/seyedi/pen/KvObJq",
    importance: "high",
    sparkJoy: false,
    where: "Projects",
    component: "Input",
    reference: false,
  },
  {
    title: "stepper",
    link: "https://codepen.io/jcoulterdesign/pen/zdwajv",
    importance: "med",
    sparkJoy: true,
    where: "Features",
    component: "Stepper",
    reference: false,
  },
  {
    title: "search",
    link: "https://codepen.io/jkantner/pen/eYmvvqQ",
    importance: "",
    sparkJoy: false,
    where: "Projects",
    component: "Input",
    reference: false,
  },
  {
    title: "Cursor Tool",
    link: "https://codepen.io/ethanselzer/pen/ryayLK",
    importance: "",
    sparkJoy: false,
    where: "",
    component: "Cursor",
    reference: true,
  },
  {
    title: "currenttask",
    link: "https://codepen.io/StephenScaff/pen/egOedp",
    importance: "",
    sparkJoy: false,
    where: "",
    component: "Card",
    reference: false,
  },
  {
    title: "currenttask",
    link: "https://codepen.io/noeldelgado/pen/PZJGLx",
    importance: "",
    sparkJoy: false,
    where: "",
    component: "Cursor",
    reference: false,
  },
  {
    title: "animation keyframes",
    link: "https://codepen.io/prvnbist/pen/zRMaeK",
    importance: "https://codepen.io/du5rte/pen/KrGjEm",
    sparkJoy: true,
    where: "",
    component: "All",
    reference: true,
  },
  {
    title: "cursorhighlight",
    link: "https://codepen.io/andrewchmr-the-vuer/pen/GRZjbbB",
    importance: "high",
    sparkJoy: true,
    where: "All",
    component: "Cursor",
    reference: true,
  },
  {
    title: "cursorhighlight",
    link: "https://codesandbox.io/embed/cursor-y71mi",
    importance: "",
    sparkJoy: false,
    where: "",
    component: "Cursor",
    reference: false,
  },
  {
    title: "Back and Forth Cursor",
    link: "https://codesandbox.io/embed/react-custom-cursor-2v06n",
    importance: "",
    sparkJoy: true,
    where: "All",
    component: "Cursor",
    reference: false,
  },
  {
    title: "JS Array instructions",
    link: "https://codepen.io/sdras/pen/gogVRX",
    importance: "",
    sparkJoy: true,
    where: "Problem Solving, maybe",
    component: "NotAssigned",
    reference: false,
  },
  {
    title: "list",
    link: "https://codepen.io/aaroniker/pen/WKbzgx",
    importance: "high",
    sparkJoy: true,
    where: "Task",
    component: "DoneItem",
    reference: false,
  },
  {
    title: "list",
    link: "https://codepen.io/nerdmanship/pen/veWyKg",
    importance: "high",
    sparkJoy: false,
    where: "Task",
    component: "DoneItem",
    reference: false,
  },
  {
    title: "To Do List",
    link: "https://codepen.io/shshaw/pen/WXMdwE",
    importance: "high",
    sparkJoy: true,
    where: "Task",
    component: "DoneItem",
    reference: false,
  },
  {
    title: "list",
    link: "https://codepen.io/milanraring/pen/QWbqBGo",
    importance: "high",
    sparkJoy: false,
    where: "",
    component: "NotAssigned",
    reference: false,
  },
  {
    title: "404",
    link: "https://codepen.io/dsenneff/pen/mjZgmN",
    importance: "",
    sparkJoy: true,
    where: "Error",
    component: "Page",
    reference: false,
  },
  {
    title: "grid organize",
    link: "https://codepen.io/stacy/pen/YGxoEG",
    importance: "",
    sparkJoy: true,
    where: "All",
    component: "NotAssigned",
    reference: true,
  },
  {
    title: "gridd",
    link: "https://codepen.io/enxaneta/pen/adLPwv",
    importance: "",
    sparkJoy: false,
    where: "",
    component: "Layout",
    reference: true,
  },
  {
    title: "Walking Loader",
    link: "https://codepen.io/finnhvman/pen/bmNdNr",
    importance: "Low",
    sparkJoy: false,
    where: "All",
    component: "Loader",
    reference: false,
  },
  {
    title: "Walking Loader",
    link: "https://codepen.io/chrisgannon/pen/VvJjgY",
    importance: "",
    sparkJoy: false,
    where: "All",
    component: "Loader",
    reference: false,
  },
  {
    title: "purecssloader",
    link: "loaders",
    importance: "",
    sparkJoy: true,
    where: "",
    component: "Loader",
    reference: false,
  },
  {
    title: "purecssloader",
    link: "https://codepen.io/woodwoerk/pen/LpLwRP",
    importance: "",
    sparkJoy: false,
    where: "All",
    component: "Loader",
    reference: false,
  },
  {
    title: "navbar",
    link: "https://codesandbox.io/embed/framer-motion-animatesharedlayout-menu-underline-demo-y6tl3",
    importance: "",
    sparkJoy: true,
    where: "All",
    component: "Navbar",
    reference: false,
  },
  {
    title: "navbar",
    link: "https://codepen.io/ainalem/pen/LJYRxz",
    importance: "",
    sparkJoy: true,
    where: "All",
    component: "Button",
    reference: false,
  },
  {
    title: "loaders",
    link: "https://codepen.io/collection/HtAne?cursor:ZD0xJm89MSZwPTEmdj03MQ::",
    importance: "",
    sparkJoy: false,
    where: "",
    component: "Loader",
    reference: true,
  },
  {
    title: "Grid",
    link: "https://codepen.io/collection/XRRJGq?cursor:ZD0xJm89MSZwPTEmdj0xNQ::",
    importance: "",
    sparkJoy: false,
    where: "",
    component: "Layout",
    reference: true,
  },
  {
    title: "Grid",
    link: "https://codepen.io/collection/DgwjNL?cursor:ZD0xJm89MSZwPTEmdj04",
    importance: "",
    sparkJoy: false,
    where: "",
    component: "Layout",
    reference: true,
  },
  {
    title: "Click and Expand Card",
    link: "https://codepen.io/suez/embed/AXQaEg",
    importance: "",
    sparkJoy: true,
    where: "Project",
    component: "Card",
    reference: false,
  },
  {
    title: "Awesome Draggable Library",
    link: "https://react-beautiful-dnd.netlify.app/?path:/story/tables--with-custom-portal",
    importance: "high",
    sparkJoy: true,
    where: "",
    component: "Drag",
    reference: true,
  },
  {
    title: "Add Card and it'll slowly come out",
    link: "https://codesandbox.io/s/react-grid-layout-d9n8q",
    importance: "low",
    sparkJoy: false,
    where: "",
    component: "Card",
    reference: false,
  },
  {
    title: "Comment Card",
    link: "https://codepen.io/sdras/embed/zYqvJqy",
    importance: "low",
    sparkJoy: true,
    where: "All",
    component: "Card",
    reference: false,
  },
  {
    title: "Card click will expand",
    link: "https://codesandbox.io/s/9onoj",
    importance: "low",
    sparkJoy: false,
    where: "",
    component: "Card",
    reference: false,
  },
  {
    title: "music player",
    link: "https://codepen.io/himalayasingh/embed/QZKqOX",
    importance: "low",
    sparkJoy: true,
    where: "",
    component: "Widget",
    reference: false,
  },
];
module.exports = codepens;
