let evey = {
  // if refernce true, forget about where
  reference: false,
  sparkJoy: false,
  simple: false,
  where: "",
  component: "",
  importance: "",
};
const obj = {
  simple: true,
  reference: true,
  importance: ["high", "med", "low"],
  where: [
    "Backend",
    "All",
    "Error",
    "Navbar",
    "Home",
    "Bugs",
    "Features",
    "Projects",
    "Payment",
    "Settings",
    "Tasks",
    "Calendar",
    "Past Projects",
    "About",
    "Signup",
    "Login",
  ],
  component: [
    "Picker",
    "Scroll",
    "Dropdown",
    "Modal",
    "Transition",
    "Rating",
    "Information",
    "Data",
    "Drag",
    "Form",
    "List",
    "Image",
    "Database",
    "Cursor",
    "DoneItem",
    "Checkbox",
    "Page",
    "Calendar",
    "Button",
    "Navbar",
    "Text",
    "Layout",
    "List",
    "Card",
    "Progress",
    "Table",
    "Input",
  ],
};
