export const INIT_SETTINGS = [
  {
    id: 1,
    user_id: 1,
    photo: "",
    firstName: "",
    lastName: "",
    company: "",
    location: "",
    about: "",
    notifications: false,
    cookies: false,
    ads: false,
  },
  {
    id: 2,
    user_id: 2,
    photo: "",
    firstName: "",
    lastName: "",
    company: "",
    location: "",
    about: "",
    notifications: false,
    cookies: false,
    ads: false,
  },
  {
    id: 3,
    user_id: 3,
    photo: "",
    firstName: "",
    lastName: "",
    company: "",
    location: "",
    about: "",
    notifications: false,
    cookies: false,
    ads: false,
  },
  {
    id: 4,
    user_id: 4,
    photo: "",
    firstName: "",
    lastName: "",
    company: "",
    location: "",
    about: "",
    notifications: false,
    cookies: false,
    ads: false,
  },
];
